builds:
- binary: postmanify
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  main: ./cmd/postmanify/main.go
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
    - "seblegall/postmanify:latest"
    - "seblegall/postmanify:{{ .Tag }}"
    - "seblegall/postmanify:v{{ .Major }}"