builds:
- binary: postmanify
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  main: ./cmd/postmanify/main.go
# archive:
#   replacements:
#     darwin: macos
#     linux: linux
#     windows: windows
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
